### PR TITLE
Bind call implemented

### PR DESCRIPTION
**Pull request by fnk93**
Bind Guest_id to an existing hive_id.

Regarding #16

### CODE REVIEW

**Comment by laoli4121** [comment]
run a.bind(guest_id,uid) but failed with authentication error.
Need any prestep to do?

**Comment by fnk93** [comment]
Need to look into it. For sure you'll have to login into the guest account first

**Comment by laoli4121** [comment]
Any idea about this? By the way, how do you know the api scheme? like parameters, format, urls...

**Comment by fnk93** [comment]
When I logged it was like this:
- hub.qpyou.cn/guest/login_proc (POST-Request to login with created hive account)
- summonerswar-xx.qpyou.cn/api/gateway_c2.php (POST-Request: CheckCandidateUid)
- hub.qpyou.cn/guest/bind/xxxxxxxxx/xxxxxxx (POST-Request to bind guest account to hive account)
- summonerswar-xx.qpyou.cn/api/gateway_c2.php (POST-Request: ProcessGuestTransition)
and afterwards the standard login procedure.

I don't know the api scheme, but I do log the network traffic and try to find out what is going on in the game's background.

**Comment by laoli4121** [comment]
Yeah but I cannot grab the network data via proxy tool when connecting to hub.qpyou.cn, so it's a obstacle to perform the post function

**Comment by laoli4121** [comment]
May I have the parameter of CheckCandidateUid and ProcessGuestTransition post request
,please? Cause I cannot logged the game data out.

**Comment by fnk93** [comment]
Yeah, hub.qpyou.cn ist using https and the app itself is using certificate pinning and is protected by appguard.
Nonetheless, the parameters are present in my fork in the api.py.

**Comment by Raklure** [comment]
Has anyone managed to find out how to bind the guest account to an hive ID ?
This is the only thing that we need that could make the bot actually useful
The thing is that the request we use in your bind() function has no right to access the hub.qpyou.cn/guest/bind, I'm trying to figure out how could we access it but it's no easy job.

**Pull request closed without merging**
